set_property SRC_FILE_INFO {cfile:D:/ps_pl_bram/ps_pl_bram.srcs/constrs_1/new/bram.xdc rfile:D:/ps_pl_bram/ps_pl_bram.srcs/constrs_1/new/bram.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list systembram_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {systembram_i/blk_mem_gen_0/U0/doutb[0]} {systembram_i/blk_mem_gen_0/U0/doutb[1]} {systembram_i/blk_mem_gen_0/U0/doutb[2]} {systembram_i/blk_mem_gen_0/U0/doutb[3]} {systembram_i/blk_mem_gen_0/U0/doutb[4]} {systembram_i/blk_mem_gen_0/U0/doutb[5]} {systembram_i/blk_mem_gen_0/U0/doutb[6]} {systembram_i/blk_mem_gen_0/U0/doutb[7]} {systembram_i/blk_mem_gen_0/U0/doutb[8]} {systembram_i/blk_mem_gen_0/U0/doutb[9]} {systembram_i/blk_mem_gen_0/U0/doutb[10]} {systembram_i/blk_mem_gen_0/U0/doutb[11]} {systembram_i/blk_mem_gen_0/U0/doutb[12]} {systembram_i/blk_mem_gen_0/U0/doutb[13]} {systembram_i/blk_mem_gen_0/U0/doutb[14]} {systembram_i/blk_mem_gen_0/U0/doutb[15]} {systembram_i/blk_mem_gen_0/U0/doutb[16]} {systembram_i/blk_mem_gen_0/U0/doutb[17]} {systembram_i/blk_mem_gen_0/U0/doutb[18]} {systembram_i/blk_mem_gen_0/U0/doutb[19]} {systembram_i/blk_mem_gen_0/U0/doutb[20]} {systembram_i/blk_mem_gen_0/U0/doutb[21]} {systembram_i/blk_mem_gen_0/U0/doutb[22]} {systembram_i/blk_mem_gen_0/U0/doutb[23]} {systembram_i/blk_mem_gen_0/U0/doutb[24]} {systembram_i/blk_mem_gen_0/U0/doutb[25]} {systembram_i/blk_mem_gen_0/U0/doutb[26]} {systembram_i/blk_mem_gen_0/U0/doutb[27]} {systembram_i/blk_mem_gen_0/U0/doutb[28]} {systembram_i/blk_mem_gen_0/U0/doutb[29]} {systembram_i/blk_mem_gen_0/U0/doutb[30]} {systembram_i/blk_mem_gen_0/U0/doutb[31]}]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {systembram_i/blk_mem_gen_0/U0/addrb[2]} {systembram_i/blk_mem_gen_0/U0/addrb[3]} {systembram_i/blk_mem_gen_0/U0/addrb[4]} {systembram_i/blk_mem_gen_0/U0/addrb[5]} {systembram_i/blk_mem_gen_0/U0/addrb[6]} {systembram_i/blk_mem_gen_0/U0/addrb[7]} {systembram_i/blk_mem_gen_0/U0/addrb[8]} {systembram_i/blk_mem_gen_0/U0/addrb[9]} {systembram_i/blk_mem_gen_0/U0/addrb[10]} {systembram_i/blk_mem_gen_0/U0/addrb[11]} {systembram_i/blk_mem_gen_0/U0/addrb[12]}]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list systembram_i/blk_mem_gen_0/U0/enb]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
