# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/systembram/ip/systembram_blk_mem_gen_0_0/systembram_blk_mem_gen_0_0.xci
# IP: The module: 'systembram_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ps_pl_bram/ps_pl_bram.gen/sources_1/bd/systembram/ip/systembram_blk_mem_gen_0_0/systembram_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'systembram_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/systembram/ip/systembram_blk_mem_gen_0_0/systembram_blk_mem_gen_0_0.xci
# IP: The module: 'systembram_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ps_pl_bram/ps_pl_bram.gen/sources_1/bd/systembram/ip/systembram_blk_mem_gen_0_0/systembram_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'systembram_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
