# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/ps_pl_bram/ps_pl_bram.srcs/constrs_1/new/bram.xdc

# Block Designs: D:/ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/systembram/systembram.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==systembram || ORIG_REF_NAME==systembram} -quiet] -quiet

# IP: D:/ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/systembram/ip/systembram_processing_system7_0_0/systembram_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==systembram_processing_system7_0_0 || ORIG_REF_NAME==systembram_processing_system7_0_0} -quiet] -quiet

# IP: D:/ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/systembram/ip/systembram_axi_bram_ctrl_0_0/systembram_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==systembram_axi_bram_ctrl_0_0 || ORIG_REF_NAME==systembram_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: D:/ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/systembram/ip/systembram_blk_mem_gen_0_0/systembram_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==systembram_blk_mem_gen_0_0 || ORIG_REF_NAME==systembram_blk_mem_gen_0_0} -quiet] -quiet

# IP: D:/ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/systembram/ip/systembram_axi_smc_1/systembram_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==systembram_axi_smc_1 || ORIG_REF_NAME==systembram_axi_smc_1} -quiet] -quiet

# IP: D:/ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/systembram/ip/systembram_rst_ps7_0_50M_1/systembram_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==systembram_rst_ps7_0_50M_1 || ORIG_REF_NAME==systembram_rst_ps7_0_50M_1} -quiet] -quiet

# IP: D:/ps_pl_bram/ps_pl_bram.srcs/sources_1/bd/systembram/ip/systembram_pl_bram_rd_0_0/systembram_pl_bram_rd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==systembram_pl_bram_rd_0_0 || ORIG_REF_NAME==systembram_pl_bram_rd_0_0} -quiet] -quiet

# XDC: d:/ps_pl_bram/ps_pl_bram.gen/sources_1/bd/systembram/systembram_ooc.xdc
